"""Eliminar campos CAPTCHA de la base de datos

Revision ID: 319ed50f640d
Revises: 
Create Date: 2025-11-22 19:49:46.588857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '319ed50f640d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_servicios', schema=None) as batch_op:
        batch_op.drop_column('captcha_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha_token', mysql.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
