from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c03eb21def66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_servicios', sa.Column('nombre_contacto', sa.String(length=100), nullable=True))
    op.add_column('solicitudes_servicios', sa.Column('email_contacto', sa.String(length=100), nullable=True))
    op.add_column('solicitudes_servicios', sa.Column('telefono_contacto', sa.String(length=20), nullable=True))
    op.add_column('solicitudes_servicios', sa.Column('area_servicio', sa.String(length=100), nullable=True))
    op.add_column('solicitudes_servicios', sa.Column('detalle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes_servicios', 'detalle')
    op.drop_column('solicitudes_servicios', 'area_servicio')
    op.drop_column('solicitudes_servicios', 'telefono_contacto')
    op.drop_column('solicitudes_servicios', 'email_contacto')
    op.drop_column('solicitudes_servicios', 'nombre_contacto')
    # ### end Alembic commands ###